-- Cliento CRM - Initial Database Schema
-- This migration sets up the core tables for multi-tenancy and user management.

-- Create a custom type for user roles within an organization.
-- SUPER_ADMIN is managed outside this system (e.g., via Supabase custom claims or config).
CREATE TYPE public.user_role AS ENUM (
    'ORG_ADMIN',
    'TEAM_MEMBER',
    'CLIENT'
);

-- 1. Organizations Table
-- Stores information about each tenant (organization) in the system.
CREATE TABLE public.organizations (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.organizations IS 'Represents a single tenant (organization) in the multi-tenant system.';

-- 2. Profiles Table
-- Extends Supabase's auth.users table with public-facing and app-specific data.
-- Each user has a primary organization they belong to.
CREATE TABLE public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name text,
    avatar_url text,
    organization_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.profiles IS 'Stores public-facing and application-specific user data, linked to auth.users.';

-- 3. User Roles Junction Table
-- Assigns roles to users within specific organizations. This structure allows a user
-- to potentially have roles in multiple organizations, providing flexibility.
CREATE TABLE public.user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    role public.user_role NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    -- A user can only have a specific role once within the same organization.
    CONSTRAINT user_organization_role_unique UNIQUE (user_id, organization_id, role)
);
COMMENT ON TABLE public.user_roles IS 'Assigns roles to users for specific organizations.';


-- ROW-LEVEL SECURITY (RLS) POLICIES
-- These are critical for ensuring data is isolated between tenants.

-- RLS for Organizations
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
-- For now, we'll allow users to see the organization they belong to.
-- A more complex policy would allow admins to see their organization.
-- This will be refined later. For now, authenticated users can read.
CREATE POLICY "Authenticated users can view organizations" ON public.organizations
FOR SELECT USING (auth.role() = 'authenticated');


-- RLS for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
-- Users can view their own profile.
CREATE POLICY "Users can view their own profile" ON public.profiles
FOR SELECT USING (auth.uid() = id);
-- Users can update their own profile.
CREATE POLICY "Users can update their own profile" ON public.profiles
FOR UPDATE USING (auth.uid() = id);
-- Org members can view profiles of other users in the same organization.
CREATE POLICY "Users can view profiles of others in their organization" ON public.profiles
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.profiles p
        WHERE p.id = auth.uid() AND p.organization_id = organization_id
    )
);

-- RLS for User Roles
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
-- Users can view their own roles.
CREATE POLICY "Users can view their own roles" ON public.user_roles
FOR SELECT USING (auth.uid() = user_id);
-- Org Admins should be able to manage roles in their org. This will be added later.
-- For now, this allows users to know their permissions.
CREATE POLICY "Org members can view roles within their organization" ON public.user_roles
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.profiles p
        WHERE p.id = auth.uid() AND p.organization_id = user_roles.organization_id
    )
);
